# Generated by Django 3.2.5 on 2021-07-30 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monthly',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('e_no', models.CharField(max_length=20)),
                ('e_name', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('no_roaster_deviation', models.CharField(max_length=20)),
                ('roaster_deviation', models.CharField(max_length=20)),
                ('training_session', models.CharField(max_length=20)),
                ('absent', models.CharField(max_length=20)),
                ('offday', models.CharField(max_length=20)),
                ('present', models.CharField(max_length=20)),
                ('overtime_hours', models.CharField(max_length=20)),
                ('safety_risk_rating', models.CharField(max_length=20)),
                ('leaves', models.CharField(max_length=20)),
                ('bonus', models.CharField(max_length=20, null=True)),
                ('bonus_score', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'monthly',
            },
        ),
        migrations.CreateModel(
            name='predResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('e_no', models.CharField(max_length=20)),
                ('month', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('score', models.CharField(max_length=20)),
                ('bonus_score', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'prediction_results',
            },
        ),
        migrations.CreateModel(
            name='Yearly',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('e_no', models.CharField(max_length=20)),
                ('e_name', models.CharField(max_length=20)),
                ('grade', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('no_roaster_deviation', models.CharField(max_length=20)),
                ('roaster_deviation', models.CharField(max_length=20)),
                ('training_session', models.CharField(max_length=20)),
                ('absent', models.CharField(max_length=20)),
                ('offday', models.CharField(max_length=20)),
                ('present', models.CharField(max_length=20)),
                ('overtime_hours', models.CharField(max_length=20)),
                ('safety_risk_rating', models.CharField(max_length=20)),
                ('leaves', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'yearly',
            },
        ),
    ]
